const {chromium}=require('/Users/jjzhang/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Users/jjzhang/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell'});const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.getByRole('button',{name:'运营老师',exact:true}).click();await page.getByRole('button',{name:'填入运营示例账号',exact:true}).click();await page.getByRole('button',{name:'登录工作空间',exact:true}).click();await page.getByText('早上好，陈老师').waitFor();const go=async(route)=>{await page.evaluate(r=>location.hash='/'+r,route);await page.waitForTimeout(180);};
const routes=['dashboard','programs','programs/bpa','students','students/DEMO-0002','teams','teams/T001','courses','courses/C1','resources','feedback','feedback/new','students/new','courses/new','resources/upload','analytics','announcements','profile','login'];
for(const [width,height] of [[320,740],[375,812],[390,844],[430,932],[768,1024],[1024,768],[1440,900],[812,375]]){await page.setViewportSize({width,height});for(const route of routes){await go(route);await page.locator('h1').first().waitFor();const overflow=await page.evaluate(()=>({vw:innerWidth,sw:document.documentElement.scrollWidth}));assert(overflow.sw<=width+1,`overflow ${width} ${route} ${overflow.sw}`);}results.push(`layout ${width}x${height}: ${routes.length} routes passed`)}
await page.setViewportSize({width:390,height:844});await go('login');await page.getByRole('button',{name:'销售顾问',exact:true}).click();await page.getByRole('button',{name:'填入销售示例账号',exact:true}).click();await page.getByRole('button',{name:'登录工作空间',exact:true}).click();await page.getByText('早上好，Alex').waitFor();results.push('sales demo login');
await go('programs');await page.getByRole('textbox',{name:'搜索项目，例如 BPA'}).fill('BPA');assert.equal(await page.locator('.program-card').count(),1);await page.getByRole('button',{name:'查看项目详情'}).click();await page.getByRole('tab',{name:'招生资料',exact:true}).click();await page.getByRole('button',{name:'预览BPA 项目招生手册',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.locator('iframe').getAttribute('src'),'/materials/R1.pdf');const [dl]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'下载文件',exact:true}).click()]);assert(await dl.path());await page.getByRole('button',{name:'Close',exact:true}).click();results.push('sales BPA search, preview and PDF download');
await go('students');assert.equal(await page.locator('.student-card').count(),10);assert(!await page.getByText('示例·林知夏',{exact:true}).isVisible());await page.getByRole('textbox',{name:'搜索学生姓名或编号'}).fill('陈星野');await page.locator('.student-card').first().click();await page.getByRole('tab',{name:'教学反馈',exact:true}).click();await page.getByText('完成了研究问题的初步定义',{exact:false}).waitFor();assert.equal(await page.getByRole('button',{name:'保存状态',exact:true}).count(),0);await go('students/DEMO-0001');assert.equal(await page.getByRole('heading',{name:'示例·林知夏',exact:true}).count(),0);results.push('sales student scope, feedback and direct-route guard');
await go('profile');await page.getByRole('button',{name:'返回登录页 / 切换账号',exact:true}).click();await page.getByRole('button',{name:'运营老师',exact:true}).click();await page.getByRole('button',{name:'填入运营示例账号',exact:true}).click();await page.getByRole('button',{name:'登录工作空间',exact:true}).click();await go('teams?attention');assert.equal(await page.locator('.team-card').count(),3);await page.locator('.team-card').first().click();await page.getByRole('tab',{name:'运营记录',exact:true}).click();await page.getByRole('textbox',{name:'运营备注'}).fill('验收备注：已联系队伍补齐财务预测。');await page.getByRole('button',{name:'保存记录'}).click();await go('teams/T001');await page.getByRole('tab',{name:'运营记录',exact:true}).click();assert.equal(await page.getByRole('textbox',{name:'运营备注'}).inputValue(),'验收备注：已联系队伍补齐财务预测。');results.push('operations attention teams and notes');
await go('students/DEMO-0002');await page.getByRole('combobox',{name:'更新项目状态'}).click();await page.getByRole('option',{name:'暂停中',exact:true}).click();await page.getByRole('button',{name:'保存状态',exact:true}).click();await go('students/DEMO-0002');assert(await page.locator('.detail-hero').getByText('暂停中',{exact:true}).isVisible());results.push('operations student status persisted in session');
await go('feedback/new');await page.getByRole('textbox',{name:'学习表现、本次完成内容与当前问题'}).fill('验收反馈：完成商业分析，参与积极，待完善研究结论。');await page.getByRole('textbox',{name:'下一步安排'}).fill('下次课前补充三份研究资料。');await page.getByRole('button',{name:'保存反馈',exact:true}).click();await page.getByRole('tab',{name:'教学反馈',exact:true}).click();await page.getByText('验收反馈：完成商业分析，参与积极，待完善研究结论。',{exact:true}).waitFor();results.push('operations course feedback');
await go('students');await page.getByRole('button',{name:'筛选',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:/查看 .* 位学生/}).click();await page.getByRole('textbox',{name:'搜索学生姓名或编号'}).fill('does-not-exist');await page.getByText('暂无匹配内容',{exact:true}).waitFor();results.push('bottom sheet and empty search');
await go('courses?date=2026-10-01');await page.getByRole('heading',{name:'当天暂无课程',exact:true}).waitFor();results.push('empty calendar');
await go('dashboard');await context.setOffline(true);await page.getByText('网络已断开。',{exact:false}).waitFor();await context.setOffline(false);results.push('offline banner');
await page.evaluate(()=>document.documentElement.style.fontSize='32px');for(const route of ['dashboard','programs','students','teams','courses','resources','feedback/new']){await go(route);const width=await page.evaluate(()=>document.documentElement.scrollWidth);assert(width<=391,`200% text overflow ${route} ${width}`)}await page.evaluate(()=>document.documentElement.style.fontSize='');results.push('200% root font smoke check');
await go('dashboard');await page.screenshot({path:'/private/tmp/nexus-mobile-final.png'});await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'/private/tmp/nexus-desktop-final.png'});await go('programs');await page.screenshot({path:'/private/tmp/nexus-programs.png'});assert.deepEqual(errors,[]);console.log(JSON.stringify({results,browserErrors:errors},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
