'use client';
import { useEffect,useState,lazy,Suspense } from 'react';
import { LayoutDashboard,Layers,Users,UsersRound,CalendarDays,MessageSquare,FolderOpen,ChartNoAxesCombined,Megaphone,Settings2,Search,Bell,Plus,MoreHorizontal,LogOut,WifiOff,UserRound,ListTodo,Clock,MessageSquareText,ShieldCheck } from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarTrigger} from '@/components/ui/sidebar';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import Login from '@/components/nexus/login';
import {BrandMark} from '@/components/nexus/brand';
import SalesHome from '@/components/nexus/recruitment';
import Dashboard from '@/components/nexus/dashboard';
import LiquidGlassLayer from '@/components/nexus/liquid-glass';
import {Provider,useNexus,useVisible} from '@/lib/nexus/store';
import {announcements} from '@/lib/nexus/data';
import {APP_ENV} from '@/lib/nexus/api';
import {roleLabels,canManageSystem} from '@/lib/nexus/roles';
import {PasswordGate} from '@/components/nexus/password';
const Modules=lazy(()=>import('@/components/nexus/modules'));
const navs=[['dashboard','工作台',LayoutDashboard],['todos','待办事项',ListTodo],['programs','项目中心',Layers],['students','学生管理',Users],['teams','队伍管理',UsersRound],['courses','课程管理',CalendarDays],['feedback','教学反馈',MessageSquare],['resources','资料中心',FolderOpen],['analytics','运营概览',ChartNoAxesCombined],['announcements','项目公告',Megaphone],['profile','个人设置',Settings2],['lessons','课时记录',Clock],['lesson-feedback','课情反馈',MessageSquareText],['admin','系统管理',ShieldCheck]] as const;
function App(){const s=useNexus(),v=useVisible(),page=s.route.split(/[/?]/)[0],sales=s.role==='sales';const [search,setSearch]=useState(false),[notices,setNotices]=useState(false),[read,setRead]=useState(false),[quick,setQuick]=useState(false),[logout,setLogout]=useState(false),[offline,setOffline]=useState(false);const user=s.user?.name||(sales?'Alex':'老师'),initial=user.slice(0,1);const navigate=(r:string)=>{setSearch(false);setQuick(false);setNotices(false);s.go(r)};
useEffect(()=>{document.documentElement.dataset.workspace=s.role==='sales'?'sales':'ops'},[s.role]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(x=>!x)}};const connection=()=>setOffline(!navigator.onLine);const viewport=()=>document.documentElement.classList.toggle('keyboard-open',!!window.visualViewport&&window.innerHeight-window.visualViewport.height>160);document.addEventListener('keydown',key);window.addEventListener('online',connection);window.addEventListener('offline',connection);window.visualViewport?.addEventListener('resize',viewport);connection();return()=>{document.removeEventListener('keydown',key);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);window.visualViewport?.removeEventListener('resize',viewport)}},[]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool||!s.authenticated)return;const lifecycle=new AbortController();const tools=[{name:'nexus_search_programs',title:'搜索项目',description:'按名称查找工作空间中的项目，返回可导航的项目标识。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:async(input:unknown)=>{const x=input as {query?:unknown};if(typeof x.query!=='string')throw new Error('query must be a string');return s.programs.filter(p=>(p.name+p.en).toLowerCase().includes((x.query as string).toLowerCase())).map(p=>({id:p.id,name:p.name,status:p.status}))}},{name:'nexus_open_program',title:'打开项目',description:'打开指定项目的详情页面，不更改业务记录。',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const x=input as {id?:unknown};if(typeof x.id!=='string'||!s.programs.some(p=>p.id===x.id))throw new Error('Unknown program');s.go('programs/'+x.id);await new Promise(resolve=>setTimeout(resolve,100));return {opened:x.id}}}];tools.forEach(t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}});return()=>lifecycle.abort()},[s.programs,s.authenticated]);
const loading=<div className="loading-state" aria-label="正在加载页面"><Skeleton className="h-10 w-48"/><Skeleton className="h-60 w-full"/></div>;
if(s.restoring)return <div className="loading-state" aria-label="正在恢复登录状态"><Skeleton className="h-10 w-48"/><Skeleton className="h-60 w-full"/></div>;
if(!s.authenticated||page==='login')return <><Login/><Toaster richColors position="top-center"/></>;
if(s.user?.mustChangePassword)return <><PasswordGate/><Toaster richColors position="top-center"/></>;
const groups=sales?[{label:'',items:navs.filter(([id])=>['dashboard','programs','students','resources'].includes(id))}]:[{label:'工作台',items:navs.filter(([id])=>['dashboard','todos'].includes(id))},{label:'',items:navs.filter(([id])=>['programs'].includes(id))},{label:'OPERATIONS 项目运营',items:['students','teams','courses','lessons','lesson-feedback','feedback','resources'].map(k=>navs.find(([id])=>id===k)!)},{label:'MANAGEMENT 管理中心',items:['analytics','announcements',...(canManageSystem(s.role)?['admin']:[]),'profile'].map(k=>navs.find(([id])=>id===k)!)}];
return <SidebarProvider style={{'--sidebar-width':'236px'} as React.CSSProperties}><a className="skip-link" href="#main">跳到主要内容</a><Sidebar variant="floating" collapsible="icon" className="nexus-sidebar"><SidebarHeader><BrandMark/></SidebarHeader><SidebarContent>{groups.map(group=><SidebarGroup key={group.label||'main'}>{group.label&&<SidebarGroupLabel>{group.label}</SidebarGroupLabel>}<SidebarMenu>{group.items.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className="nav-button" tooltip={label} aria-label={sales&&id==='students'?'我的学生':label} isActive={page===id||(id==='todos'&&page==='todos-done')} onClick={()=>s.go(id)}><Icon/><span>{sales&&id==='students'?'我的学生':label}</span>{id==='programs'&&<em>{s.programs.length}</em>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><div className="user-block"><button className="profile-trigger" onClick={()=>s.go('profile')}><span className="avatar">{initial}</span><div>{user}<small>{roleLabels[s.role]}</small></div></button><button className="icon-button" aria-label="退出登录" onClick={()=>setLogout(true)}><LogOut size={16}/></button></div></SidebarFooter></Sidebar><div className="app-body"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="collapse-trigger"/>工作空间 <span>/</span> <b>{sales&&page==='students'?'我的学生':navs.find(([id])=>id===page)?.[1]||'工作台'}</b>{APP_ENV&&APP_ENV!=='production'&&<em className="env-badge" title="开发环境：数据与生产环境隔离">DEV</em>}</div><div className="topbar-actions"><button className="global-search" aria-label="全局搜索" onClick={()=>setSearch(true)}><Search size={16}/><span>搜索项目、学生或资料</span><kbd>⌘ K</kbd></button>{!sales&&<button className="primary compact" onClick={()=>setQuick(true)}><Plus size={16}/>快速新建</button>}<button className="icon-button" aria-label="通知中心" onClick={()=>setNotices(true)}><Bell size={20}/>{!read&&announcements.length>0&&<i/>}</button><button className="avatar top-avatar" aria-label="个人资料" onClick={()=>s.go('profile')}>{initial}</button></div></header>{offline&&<div role="status" className="offline-banner"><WifiOff size={17}/>网络已断开。已加载的数据仍可查看，修改将在恢复连接后再保存。</div>}<main id="main" className="main-content">{page==='dashboard'?(sales?<SalesHome/>:<Dashboard role={s.role} programs={s.programs} students={v.students} teams={v.teams} courses={v.courses} go={s.go}/>):<Suspense fallback={loading}><Modules key={s.route}/></Suspense>}</main></div><nav className="bottom-nav" aria-label="移动端主导航">{[...(sales?['dashboard','programs','students','resources']:['dashboard','todos','programs','lessons']).map(k=>navs.find(([id])=>id===k)!),['profile',sales?'我的':'更多',sales?UserRound:MoreHorizontal] as const].map(([id,label,Icon])=><button key={id} aria-current={page===id?'page':undefined} className={page===id?'active':''} onClick={()=>s.go(id)}><Icon size={21}/><span>{id==='dashboard'?(sales?'首页':'工作台'):label.replace('管理','').replace('中心','')}</span></button>)}</nav>
<CommandDialog open={search} onOpenChange={setSearch} title="全局搜索" description={sales?'查找项目、我的学生与授权资料':'查找当前账号有权查看的项目、学生、队伍、课程与资料'}><CommandInput placeholder={sales?'搜索项目、我的学生或资料…':'搜索项目、学生、队伍或资料…'}/><CommandList><CommandEmpty>没有找到匹配结果</CommandEmpty><CommandGroup heading="项目">{s.programs.map(p=><CommandItem key={p.id} value={p.name+' '+p.en} onSelect={()=>navigate('programs/'+p.id)}><Layers/>{p.name}</CommandItem>)}</CommandGroup><CommandGroup heading="学生">{v.students.map(x=><CommandItem key={x.id} value={x.name+' '+x.id} onSelect={()=>navigate('students/'+x.id)}><Users/>{x.name}</CommandItem>)}</CommandGroup>{!sales&&<><CommandGroup heading="队伍">{v.teams.map(t=><CommandItem key={t.id} value={t.name} onSelect={()=>navigate('teams/'+t.id)}><UsersRound/>{t.name}</CommandItem>)}</CommandGroup><CommandGroup heading="课程">{v.courses.map(c=><CommandItem key={c.id} value={c.id+' '+c.name+' '+c.date} onSelect={()=>navigate('courses/'+c.id)}><CalendarDays/>{c.name} · {c.date}</CommandItem>)}</CommandGroup></>}<CommandGroup heading="资料">{v.files.map(f=><CommandItem key={f.id} value={f.name} onSelect={()=>navigate('resources?program='+f.program)}><FolderOpen/>{f.name}</CommandItem>)}</CommandGroup></CommandList></CommandDialog>
<Dialog open={notices} onOpenChange={setNotices}><DialogContent className="notice-dialog"><DialogHeader><DialogTitle>通知中心</DialogTitle><DialogDescription>{!announcements.length?'暂无通知':read?'所有通知已读':`你有 ${announcements.length} 条项目更新`}</DialogDescription></DialogHeader>{announcements.length>0&&<button className="text-button" onClick={()=>{setRead(true);toast.success('全部通知已标记为已读')}}>全部标为已读</button>}{announcements.filter((_,index)=>!sales||index===0).map(a=><button className="notification" key={a.title} onClick={()=>{setRead(true);navigate('programs/'+a.program)}}><Megaphone size={19}/><div><strong>{a.title}</strong><p>{a.text}</p><small>{a.date}</small></div></button>)}</DialogContent></Dialog>
<Sheet open={quick} onOpenChange={setQuick}><SheetContent side="bottom" className="bottom-sheet"><SheetHeader><SheetTitle>快速新建</SheetTitle><SheetDescription>为下一次协作做好准备</SheetDescription></SheetHeader><div className="more-grid">{[['lessons?new','记录课时'],['lesson-feedback?new','课情反馈'],['students/new','新增学生'],['teams/new','新建队伍'],['courses/new','新建课程'],['resources/upload','上传资料']].map(([r,l])=><button key={r} className="secondary" onClick={()=>navigate(r)}><Plus size={18}/>{l}</button>)}</div></SheetContent></Sheet>
<AlertDialog open={logout} onOpenChange={setLogout}><AlertDialogContent><AlertDialogTitle>确定退出当前账号？</AlertDialogTitle><AlertDialogDescription>你将返回登录页面。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{setLogout(false);setSearch(false);setNotices(false);setQuick(false);s.logout();s.go('login')}}>退出登录</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="top-center"/><LiquidGlassLayer enabled={sales}/></SidebarProvider>}
export default function Home(){return <Provider><App/></Provider>}
