#!/usr/bin/env bash
# One-time (idempotent) provisioning of a TencentOS / RHEL-like server for PROJECT NEXUS.
# Run as root ON THE SERVER:  bash server-setup.sh
# Creates: PostgreSQL 16 (localhost only) with nexus_prod / nexus_dev databases and users,
# /opt/nexus/{prod,dev}/.env (mode 600, random secrets), systemd units nexus-api-{prod,dev},
# nginx (prod on :80, dev on :8080, API under /api). Existing secrets are never regenerated.
set -euo pipefail
[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }

echo "== packages"
if ! command -v node >/dev/null || ! node -v | grep -q '^v22'; then dnf -y -q module reset nodejs; dnf -y -q module enable nodejs:22; dnf -y -q install nodejs; fi
if ! command -v psql >/dev/null; then dnf -y -q module reset postgresql; dnf -y -q module enable postgresql:16; dnf -y -q install postgresql-server postgresql-contrib; fi
if ! command -v nginx >/dev/null; then dnf -y -q module reset nginx; dnf -y -q module enable nginx:1.24; dnf -y -q install nginx; fi
command -v openssl >/dev/null || dnf -y -q install openssl
command -v tar >/dev/null || dnf -y -q install tar

echo "== swap"
if ! swapon --show | grep -q .; then
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile >/dev/null && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

echo "== postgresql"
PGDATA=/var/lib/pgsql/data
[ -f "$PGDATA/PG_VERSION" ] || postgresql-setup --initdb
# Listen on localhost only; password (scram) auth for TCP clients.
sed -i "s/^#\?listen_addresses\s*=.*/listen_addresses = 'localhost'/" "$PGDATA/postgresql.conf"
sed -i "s/^#\?password_encryption\s*=.*/password_encryption = scram-sha-256/" "$PGDATA/postgresql.conf"
if ! grep -q 'nexus-managed' "$PGDATA/pg_hba.conf"; then
  cp "$PGDATA/pg_hba.conf" "$PGDATA/pg_hba.conf.orig"
  cat > "$PGDATA/pg_hba.conf" <<'HBA'
# nexus-managed: local socket for the postgres superuser, scram over loopback for apps.
local   all   postgres                 peer
local   all   all                      peer
host    all   all      127.0.0.1/32    scram-sha-256
host    all   all      ::1/128         scram-sha-256
HBA
  chown postgres:postgres "$PGDATA/pg_hba.conf"; chmod 600 "$PGDATA/pg_hba.conf"
fi
systemctl enable -q postgresql
systemctl restart postgresql

echo "== service user"
id nexus >/dev/null 2>&1 || useradd --system --home-dir /opt/nexus --shell /sbin/nologin nexus
mkdir -p /opt/nexus
chown root:root /opt/nexus; chmod 755 /opt/nexus

port_for() { [ "$1" = prod ] && echo 3001 || echo 3002; }
for ENV in prod dev; do
  echo "== environment $ENV"
  DIR=/opt/nexus/$ENV; DB=nexus_$ENV; PORT=$(port_for $ENV)
  mkdir -p "$DIR/releases"; chmod 755 "$DIR"
  if [ ! -f "$DIR/.env" ]; then
    DBPASS=$(openssl rand -hex 24); JWT=$(openssl rand -hex 48)
    umask 077
    cat > "$DIR/.env" <<ENV
# PROJECT NEXUS $ENV — generated by deploy/server-setup.sh. Keep private (mode 600).
NEXUS_ENV=$([ $ENV = prod ] && echo production || echo development)
NODE_ENV=production
HOST=127.0.0.1
PORT=$PORT
DATABASE_URL=postgres://$DB:$DBPASS@127.0.0.1:5432/$DB
JWT_SECRET=$JWT
ENV
    umask 022
  fi
  chown root:root "$DIR/.env"; chmod 600 "$DIR/.env"
  DBPASS=$(sed -n "s#^DATABASE_URL=postgres://$DB:\([^@]*\)@.*#\1#p" "$DIR/.env")
  # Role + database (password from the env file, so re-running keeps them in sync).
  sudo -u postgres psql -q -v ON_ERROR_STOP=1 -v pw="$DBPASS" <<SQL
SELECT format('CREATE ROLE %I LOGIN', '$DB') WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB')\gexec
ALTER ROLE $DB WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'pw';
SELECT format('CREATE DATABASE %I OWNER %I', '$DB', '$DB') WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DB')\gexec
REVOKE ALL ON DATABASE $DB FROM PUBLIC;
GRANT ALL ON DATABASE $DB TO $DB;
SQL
  sudo -u postgres psql -q -d "$DB" -c "ALTER SCHEMA public OWNER TO $DB;"

  cat > /etc/systemd/system/nexus-api-$ENV.service <<UNIT
[Unit]
Description=PROJECT NEXUS API ($ENV)
After=network.target postgresql.service
Requires=postgresql.service

[Service]
Type=simple
User=nexus
Group=nexus
EnvironmentFile=$DIR/.env
WorkingDirectory=$DIR/current/server
ExecStart=/usr/bin/node --enable-source-maps --max-old-space-size=192 $DIR/current/server/index.mjs
Restart=always
RestartSec=3
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadOnlyPaths=$DIR

[Install]
WantedBy=multi-user.target
UNIT
done
systemctl daemon-reload

echo "== nginx"
if [ ! -f /etc/nginx/nginx.conf.orig ]; then cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig; fi
cat > /etc/nginx/nginx.conf <<'NGX'
# Managed by PROJECT NEXUS deploy/server-setup.sh (original kept as nginx.conf.orig).
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
events { worker_connections 1024; }
http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;
    sendfile on; tcp_nopush on; keepalive_timeout 65; types_hash_max_size 4096; server_tokens off;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on; gzip_comp_level 5; gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/javascript image/svg+xml application/manifest+json;
    include /etc/nginx/conf.d/*.conf;
}
NGX
install -m 644 "$(dirname "$0")/nginx-nexus.conf" /etc/nginx/conf.d/nexus.conf
for ENV in prod dev; do
  # Placeholder page until the first deploy.
  if [ ! -e /opt/nexus/$ENV/current ]; then mkdir -p /opt/nexus/$ENV/releases/empty/web /opt/nexus/$ENV/releases/empty/server; echo "<h1>PROJECT NEXUS $ENV — awaiting first deploy</h1>" > /opt/nexus/$ENV/releases/empty/web/index.html; ln -sfn releases/empty /opt/nexus/$ENV/current; fi
done
nginx -t
systemctl enable -q nginx
systemctl restart nginx

echo "== firewall"
if systemctl is-active -q firewalld; then
  firewall-cmd -q --permanent --add-service=http; firewall-cmd -q --permanent --add-port=8080/tcp; firewall-cmd -q --reload
  echo "firewalld: opened 80 and 8080"
else
  echo "firewalld inactive (cloud security group still applies)"
fi
echo "== done. Next: scripts/deploy.sh prod|dev from a developer machine."
