'use client';
import { createContext, useContext, useState, useEffect, type ReactNode, type Dispatch, type SetStateAction } from 'react';
import * as seed from './data';
export type FileRecord=seed.Resource & {url?:string};
export type Store={enrollments:seed.Enrollment[];setEnrollments:Dispatch<SetStateAction<seed.Enrollment[]>>;role:seed.Role;setRole:Dispatch<SetStateAction<seed.Role>>;programs:seed.Program[];setPrograms:Dispatch<SetStateAction<seed.Program[]>>;students:seed.Student[];setStudents:Dispatch<SetStateAction<seed.Student[]>>;teams:seed.Team[];setTeams:Dispatch<SetStateAction<seed.Team[]>>;courses:seed.Course[];setCourses:Dispatch<SetStateAction<seed.Course[]>>;feedbacks:seed.Feedback[];setFeedbacks:Dispatch<SetStateAction<seed.Feedback[]>>;files:FileRecord[];setFiles:Dispatch<SetStateAction<FileRecord[]>>;route:string;go:(route:string)=>void;favorites:string[];setFavorites:Dispatch<SetStateAction<string[]>>;recent:string[];setRecent:Dispatch<SetStateAction<string[]>>;logs:string[];log:(s:string)=>void};
const Context=createContext<Store>(null!);
export function Provider({children}:{children:ReactNode}){const [enrollments,setEnrollments]=useState(seed.enrollments);const [role,setRole]=useState<seed.Role>('sales'),[programs,setPrograms]=useState(seed.programs),[students,setStudents]=useState(seed.students),[teams,setTeams]=useState(seed.teams),[courses,setCourses]=useState(seed.courses),[feedbacks,setFeedbacks]=useState(seed.feedbacks),[files,setFiles]=useState<FileRecord[]>(seed.resources),[route,setRoute]=useState('dashboard'),[favorites,setFavorites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]),[logs,setLogs]=useState<string[]>(['演示工作空间已就绪']);
 const go=(s:string)=>{window.location.hash='/'+s;setRoute(s);window.scrollTo({top:0,behavior:'instant'});};
 useEffect(()=>{const change=()=>{setRoute(decodeURI(location.hash.replace(/^#\/?/,''))||'dashboard');window.scrollTo(0,0)};change();window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[]);
 return <Context.Provider value={{enrollments,setEnrollments,role,setRole,programs,setPrograms,students,setStudents,teams,setTeams,courses,setCourses,feedbacks,setFeedbacks,files,setFiles,route,go,favorites,setFavorites,recent,setRecent,logs,log:(s)=>setLogs(v=>[s,...v])}}>{children}</Context.Provider>}
export const useNexus=()=>useContext(Context);
export function useVisible(){const s=useNexus();const students=s.students.filter(x=>s.role!=='sales'||x.sales==='顾问 Alex');const teams=s.teams;return {students,teams,courses:s.courses.filter(c=>s.role!=='sales'||(teams.some(t=>t.id===c.team)&&s.programs.find(p=>p.id===c.program)?.published)),files:s.files.filter(f=>s.role!=='sales'||f.public),feedbacks:s.feedbacks.filter(f=>s.role!=='sales'||(f.visible&&students.some(x=>x.id===f.student)))};}
